name: auto-release
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  auto-release:
    name: "Automatic Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - run: cd kalvara
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ../KalvaraMC.zip *
      - run: cd ..
      - run: sha1sum KalvaraMC.zip | sed -zre 's/(^[^ \s]*).*/\1/' > hash.txt
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Automatic Release"
          files: |
            LICENSE
            KalvaraMC.zip
            hash.txt
